openapi: 3.0.0
info:
  title: Kanban Task management
  description: API
  version: 0.1.9

servers:
  - url: https://kanban-back-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /boards:
    get:
      tags:
        - Board
      responses:
        "200":
          description: get boards data successfully
    post:
      tags:
        - Board
      requestBody:
        description: create new board
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                  description: Title of the new board
                  example: My New Board
                columns:
                  type: array
                  description: Array of column titles for the new board (optional)
                  items:
                    type: string
                  example: ["To Do", "In Progress", "Done"]
      responses:
        "201":
          description: create new board successfully
  /boards/{id}:
    delete:
      tags:
        - Board
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Board removed
    put:
      tags:
        - Board
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        description: create new board
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                  description: Title of the new board
                  example: My New Board
      responses:
        "200":
          description: Board updated
  /columns:
    post:
      tags:
        - Column
      requestBody:
        description: create new column
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                  description: Title of the new board
                  example: My New Board
                boardId:
                  type: string
      responses:
        "201":
          description: create new column successfully
  /columns/{columnId}:
    delete:
      tags:
        - Column
      parameters:
        - in: path
          name: columnId
          schema:
            type: string
          required: true
      requestBody:
        description: delete column
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                boardId:
                  type: string
      responses:
        "200":
          description: column removed
    put:
      tags:
        - Column
      parameters:
        - in: path
          name: columnId
          schema:
            type: string
          required: true
      requestBody:
        description: delete column
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
      responses:
        "204":
          description: column updated
  /tasks:
    post:
      tags:
        - Task
      requestBody:
        description: create new task
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                  description: Title of the new task
                  example: My New Task
                description:
                  type: string
                columnId:
                  type: string
                subtasks:
                  type: array
                  description: Array of subtasks titles for the new task
                    type: string
                  example: ["To Do", "In Progress", "Done"]
      responses:
        "201":
          description: create new task successfully
  /tasks/{taskId}:
    delete:
      tags:
        - Task
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
      requestBody:
        description: delete task
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                columnId:
                  type: string
      responses:
        "200":
          description: task removed
    put:
      tags:
        - Task
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
      requestBody:
        description: update task
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
      responses:
        "204":
          description: task updated
